version: '3'

services:
  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
  #- ./dockerdata/postgres:/var/lib/postgresql/data => Si vous voulez gérer le volume dans votre dossier de projet
    env_file: .env
    ports:
      - "5432:5432"
    # autres configurations pour PostgreSQL...
    healthcheck:
  # Permet de valider le bon fonctionnement du container
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - PGDATA=/var/lib/postgresql/data/pgdata


  django:
    build: # Ici on ne déclare pas d'image mais un build
      context: ./myGym_BackEnd/
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    #command: gunicorn --reload django_lesson_project.wsgi --bind 0.0.0.0
    volumes:
      - .:/code
    env_file: .env
    
    ports:
      - "8001:8000" # Le premier port est celui disponible sur votre PC # Le second est celui utilisé par docker dans son réseau
    depends_on:
      postgres:
        condition: service_healthy
      # Ne se lancera pas tant que la DB n'est pas correctement lancée :)

  # angular:
  #   build: # Ici on ne déclare pas d'image mais un build
  #     context: ./myGym_FrontEnd/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4200:4200"
  #   # autres configurations pour Angular...


volumes:
  postgres_data: